import {
  ToolDef,
  nullable,
  nullableInt,
  nullableNum,
  nullableBool,
  nullableStringArray,
} from './registry.js';

const WS = '/api/v1/workspaces/{__ws}';

export const epicTools: ToolDef[] = [
  {
    name: 'list_epics',
    description: 'List all epics in a project.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: {
        project_id: { type: 'string' },
        cursor: nullable('string'),
        per_page: nullableInt(),
      },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/{project_id}/epics/`,
    pathParams: ['project_id'],
    queryParams: ['cursor', 'per_page'],
  },
  {
    name: 'create_epic',
    description: 'Create a new epic in a project.',
    inputSchema: {
      type: 'object',
      required: ['project_id', 'name'],
      properties: {
        project_id: { type: 'string' },
        name: { type: 'string' },
        assignees: nullableStringArray(),
        labels: nullableStringArray(),
        description_html: nullable('string'),
        description_stripped: nullable('string'),
        estimate_point: nullable('string'),
        priority: nullable('string'),
        start_date: nullable('string'),
        target_date: nullable('string'),
        state: nullable('string'),
        parent: nullable('string'),
        point: nullableInt(),
        sort_order: nullableNum(),
        is_draft: nullableBool(),
        external_source: nullable('string'),
        external_id: nullable('string'),
        type_id: nullable('string'),
      },
    },
    method: 'POST',
    pathTemplate: `${WS}/projects/{project_id}/epics/`,
    pathParams: ['project_id'],
  },
  {
    name: 'retrieve_epic',
    description: 'Retrieve an epic by ID.',
    inputSchema: {
      type: 'object',
      required: ['project_id', 'epic_id'],
      properties: {
        project_id: { type: 'string' },
        epic_id: { type: 'string' },
      },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/{project_id}/epics/{epic_id}/`,
    pathParams: ['project_id', 'epic_id'],
  },
  {
    name: 'update_epic',
    description: 'Update an epic by ID.',
    inputSchema: {
      type: 'object',
      required: ['project_id', 'epic_id'],
      properties: {
        project_id: { type: 'string' },
        epic_id: { type: 'string' },
        name: nullable('string'),
        assignees: nullableStringArray(),
        labels: nullableStringArray(),
        description_html: nullable('string'),
        description_stripped: nullable('string'),
        estimate_point: nullable('string'),
        priority: nullable('string'),
        start_date: nullable('string'),
        target_date: nullable('string'),
        state: nullable('string'),
        parent: nullable('string'),
        point: nullableInt(),
        sort_order: nullableNum(),
        is_draft: nullableBool(),
        external_source: nullable('string'),
        external_id: nullable('string'),
        type_id: nullable('string'),
      },
    },
    method: 'PATCH',
    pathTemplate: `${WS}/projects/{project_id}/epics/{epic_id}/`,
    pathParams: ['project_id', 'epic_id'],
  },
  {
    name: 'delete_epic',
    description: 'Delete an epic by ID.',
    inputSchema: {
      type: 'object',
      required: ['project_id', 'epic_id'],
      properties: {
        project_id: { type: 'string' },
        epic_id: { type: 'string' },
      },
    },
    method: 'DELETE',
    pathTemplate: `${WS}/projects/{project_id}/epics/{epic_id}/`,
    pathParams: ['project_id', 'epic_id'],
  },
];
