import { ToolDef, nullable, nullableInt, nullableBool, nullableObject } from './registry.js';

const WS = '/api/v1/workspaces/{__ws}';

export const projectTools: ToolDef[] = [
  {
    name: 'list_projects',
    description: 'List all projects in the workspace. Call this first whenever you need a project_id to pass to other tools.',
    inputSchema: {
      type: 'object',
      properties: {
        cursor: nullable('string'),
        expand: nullable('string'),
        fields: nullable('string'),
        order_by: nullable('string'),
        per_page: nullableInt(),
      },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/`,
    pathParams: [],
    queryParams: ['cursor', 'expand', 'fields', 'order_by', 'per_page'],
  },
  {
    name: 'create_project',
    description: 'Create a new project.',
    inputSchema: {
      type: 'object',
      required: ['name', 'identifier'],
      properties: {
        name: { type: 'string' },
        identifier: { type: 'string' },
        description: nullable('string'),
        project_lead: nullable('string'),
        default_assignee: nullable('string'),
        emoji: nullable('string'),
        cover_image: nullable('string'),
        module_view: nullableBool(),
        cycle_view: nullableBool(),
        issue_views_view: nullableBool(),
        page_view: nullableBool(),
        intake_view: nullableBool(),
        guest_view_all_features: nullableBool(),
        archive_in: nullableInt(),
        close_in: nullableInt(),
        timezone: nullable('string'),
        external_source: nullable('string'),
        external_id: nullable('string'),
        is_issue_type_enabled: nullableBool(),
      },
    },
    method: 'POST',
    pathTemplate: `${WS}/projects/`,
    pathParams: [],
  },
  {
    name: 'retrieve_project',
    description: 'Retrieve a project by ID.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: { project_id: { type: 'string' } },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/{project_id}/`,
    pathParams: ['project_id'],
  },
  {
    name: 'update_project',
    description: 'Update a project by ID.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: {
        project_id: { type: 'string' },
        name: nullable('string'),
        description: nullable('string'),
        identifier: nullable('string'),
        project_lead: nullable('string'),
        default_assignee: nullable('string'),
        emoji: nullable('string'),
        cover_image: nullable('string'),
        module_view: nullableBool(),
        cycle_view: nullableBool(),
        issue_views_view: nullableBool(),
        page_view: nullableBool(),
        intake_view: nullableBool(),
        guest_view_all_features: nullableBool(),
        archive_in: nullableInt(),
        close_in: nullableInt(),
        timezone: nullable('string'),
        external_source: nullable('string'),
        external_id: nullable('string'),
        is_issue_type_enabled: nullableBool(),
        is_time_tracking_enabled: nullableBool(),
        default_state: nullable('string'),
        estimate: nullable('string'),
      },
    },
    method: 'PATCH',
    pathTemplate: `${WS}/projects/{project_id}/`,
    pathParams: ['project_id'],
  },
  {
    name: 'delete_project',
    description: 'Delete a project by ID.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: { project_id: { type: 'string' } },
    },
    method: 'DELETE',
    pathTemplate: `${WS}/projects/{project_id}/`,
    pathParams: ['project_id'],
  },
  {
    name: 'get_project_features',
    description: 'Get features of a project.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: { project_id: { type: 'string' } },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/{project_id}/features/`,
    pathParams: ['project_id'],
  },
  {
    name: 'update_project_features',
    description: 'Update features of a project.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: {
        project_id: { type: 'string' },
        epics: nullableBool(),
        modules: nullableBool(),
        cycles: nullableBool(),
        views: nullableBool(),
        pages: nullableBool(),
        intakes: nullableBool(),
        work_item_types: nullableBool(),
      },
    },
    method: 'PATCH',
    pathTemplate: `${WS}/projects/{project_id}/features/`,
    pathParams: ['project_id'],
  },
  {
    name: 'get_project_members',
    description: 'Get all members of a project.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: {
        project_id: { type: 'string' },
        params: nullableObject(),
      },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/{project_id}/members/`,
    pathParams: ['project_id'],
  },
  {
    name: 'get_project_worklog_summary',
    description: 'Get work log summary for a project.',
    inputSchema: {
      type: 'object',
      required: ['project_id'],
      properties: { project_id: { type: 'string' } },
    },
    method: 'GET',
    pathTemplate: `${WS}/projects/{project_id}/worklogs/summary/`,
    pathParams: ['project_id'],
  },
];
